### ISSUE TITLE
Create README with installation instructions 

### ISSUE THREAD

**Issue by metalmatze** [betawaffle/vscode-cue#1]
Hey, thank you for working on this. 
It would be nice for people who find this repo to be able to figure out how to install your syntax highlighting.

**Comment by betawaffle** [comment]
Honestly, I need to publish it so it can be installed directly from VSCode (and write a README too), I just haven't gotten around to that yet.

**Comment by sporkmonger** [comment]
That would be super-awesome. Lack of editor support is one of the main things making me hesitant to use cue.

**Comment by metalmatze** [comment]
Yes, that exactly the reason why I opened the issue. Right now I run VSCode by running this repo with F5 and then use CUE in the new window. I would be really awesome, if we could get this via the store directly. 
@betawaffle Do you want to do this directly, or maybe it even makes sense to have the project have access to it too?!

**Comment by betawaffle** [comment]
> @betawaffle Do you want to do this directly, or maybe it even makes sense to have the project have access to it too?!

Do I _want_ to? No. I will if I find the time, but I'd be more than happy to let anyone else do it. My plan was to transfer ownership of this repo to the CUE project, I only made this to get the most basic level of highlighting support (for the same reason y'all want it).

@mpvl: Are you ready to accept ownership of this repo yet?

**Comment by betawaffle** [comment]
> Right now I run VSCode by running this repo with F5 and then use CUE in the new window.

FWIW, you can check it out directly into you `~/.vscode/extensions` directory and it'll get picked up.

**Comment by metalmatze** [comment]
Amazing, `ln -s ~/src/github.com/betawaffle/vscode-cue ~/.vscode/extensions/cuelang-0.0.0` worked.
Maybe we can discuss with project maintainers how to move this project then? :)

**Comment by ahpook** [comment]
Hey all, I put up a PR based on the info in this thread...comments welcome at #2
