### ISSUE TITLE
Syntax highlighting fails for conjunctions / disjunctions split across multiple lines

### ISSUE THREAD

**Issue by eadlam** [betawaffle/vscode-cue#6]
**Highlights correctly:**
```
x: string | int | float
```
**Highlights incorrectly:**
```
x: string  |
   int     |
   float
```

**Comment by betawaffle** [comment]
Let me see if I can fix this today.

**Comment by betawaffle** [comment]
Hmm, I'm not able to reproduce this. This is what I see:

<img width="320" alt="Screen Shot 2020-06-20 at 7 19 09 AM" src="https://user-images.githubusercontent.com/48613/85200551-65d5ca80-b2c6-11ea-9acd-2a761676295a.png">

Am I missing something @eadlam?

**Comment by eadlam** [comment]
Ah, sorry. I was on an old commit. I can confirm latest master looks good.
