### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [betawaffle/vscode-cue#7]
I'd like to use this project to highlight CUE code on GitHub.com (cf. https://github.com/github/linguist/pull/4941), but I don't know under which license it's released. Any chance you could release it under a permissive license?

**Comment by betawaffle** [comment]
Yes, the license is MIT. I'll add a license file.

**Comment by pchaigno** [comment]
Great, thanks!

By the way, if you use the exact license text given by https://choosealicense.com/licenses/mit/, you're guaranteed that GitHub will recognize it (thanks to https://github.com/github/licensed). That helps me because Linguist perform automated license checks :-)

**Comment by betawaffle** [comment]
@pchaigno: all done, you're good to go.
